#!/usr/bin/env python

import asyncio
import websockets
import csv
from datetime import datetime

async def hello(websocket):
    # Open the CSV file in append mode
    with open('methane_data.csv', 'a', newline='') as csvfile:
        csvwriter = csv.writer(csvfile)
        
        # Write the header if the file is empty
        if csvfile.tell() == 0:
            csvwriter.writerow(['Timestamp', 'Methane PPM'])
        
        # Receive and write data to the CSV file
        ppm = await websocket.recv()
        while ppm:
            timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            csvwriter.writerow([timestamp, ppm])
            print(f"{timestamp} - Methane PPM: {ppm}")
            ppm = await websocket.recv()

async def main():
    async with websockets.serve(hello, host="192.168.0.224", port=8888):
        await asyncio.get_running_loop().create_future()  # run forever

if __name__ == "__main__":
    asyncio.run(main())
